// Code generated by protoc-gen-go.
// source: example.proto
// DO NOT EDIT!

/*
Package sample is a generated protocol buffer package.

It is generated from these files:
	example.proto

It has these top-level messages:
	Test
	Ticker
*/
package sample

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Test struct {
	Query         string    `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	PageNumber    int32     `protobuf:"varint,2,opt,name=page_number,json=pageNumber" json:"page_number,omitempty"`
	ResultPerPage int32     `protobuf:"varint,3,opt,name=result_per_page,json=resultPerPage" json:"result_per_page,omitempty"`
	Tickers       []*Ticker `protobuf:"bytes,4,rep,name=tickers" json:"tickers,omitempty"`
}

func (m *Test) Reset()                    { *m = Test{} }
func (m *Test) String() string            { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()               {}
func (*Test) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Test) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *Test) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *Test) GetResultPerPage() int32 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

func (m *Test) GetTickers() []*Ticker {
	if m != nil {
		return m.Tickers
	}
	return nil
}

type Ticker struct {
	Name  string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value float32 `protobuf:"fixed32,2,opt,name=value" json:"value,omitempty"`
}

func (m *Ticker) Reset()                    { *m = Ticker{} }
func (m *Ticker) String() string            { return proto.CompactTextString(m) }
func (*Ticker) ProtoMessage()               {}
func (*Ticker) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Ticker) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Ticker) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*Test)(nil), "sample.Test")
	proto.RegisterType((*Ticker)(nil), "sample.Ticker")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0xcb, 0x8a, 0xc2, 0x30,
	0x14, 0x86, 0x49, 0x6f, 0xc3, 0x9c, 0xd2, 0x19, 0x08, 0x2e, 0xb2, 0xb3, 0x74, 0x21, 0x59, 0x75,
	0x51, 0xdf, 0x43, 0x4a, 0xe8, 0xbe, 0xa4, 0x72, 0x28, 0x62, 0x2f, 0x31, 0x17, 0xd1, 0xa7, 0xf0,
	0x95, 0xa5, 0x89, 0xee, 0xf2, 0x7d, 0x7f, 0x16, 0xdf, 0x81, 0x02, 0x1f, 0x72, 0x56, 0x13, 0xd6,
	0x4a, 0xaf, 0x76, 0xa5, 0x99, 0xf1, 0x54, 0xbd, 0x08, 0x24, 0x1d, 0x1a, 0x4b, 0x77, 0x90, 0xde,
	0x1c, 0xea, 0x27, 0x23, 0x25, 0xe1, 0xbf, 0x22, 0x00, 0xdd, 0x43, 0xae, 0xe4, 0x88, 0xfd, 0xe2,
	0xe6, 0x01, 0x35, 0x8b, 0x4a, 0xc2, 0x53, 0x01, 0x9b, 0x3a, 0x79, 0x43, 0x0f, 0xf0, 0xaf, 0xd1,
	0xb8, 0xc9, 0xf6, 0x0a, 0x75, 0xbf, 0x0d, 0x2c, 0xf6, 0x9f, 0x8a, 0xa0, 0x5b, 0xd4, 0xad, 0x1c,
	0x91, 0x72, 0xf8, 0xb1, 0x97, 0xf3, 0x15, 0xb5, 0x61, 0x49, 0x19, 0xf3, 0xbc, 0xf9, 0xab, 0x43,
	0x41, 0xdd, 0x79, 0x2d, 0xbe, 0x73, 0xd5, 0x40, 0x16, 0x14, 0xa5, 0x90, 0x2c, 0x72, 0xc6, 0x4f,
	0x91, 0x7f, 0x6f, 0x99, 0x77, 0x39, 0x39, 0xf4, 0x29, 0x91, 0x08, 0x30, 0x64, 0xfe, 0xa8, 0xe3,
	0x3b, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x21, 0x79, 0x4b, 0xe5, 0x00, 0x00, 0x00,
}
